### ISSUE TITLE
Loads incorrect data

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/picky.json#34]
![image](https://cloud.githubusercontent.com/assets/224636/12831312/94a056ba-cb61-11e5-926c-bfe02c0f7f8a.png)

Maybe it's still pulling in localstorage when the textarea is invalid. It should clear the <code> area.

**Comment by danjford** [comment]
Ok this is an easy one, in the fail of the request there is nothing to clear the data of `code`'s value if it has found it's incorrect.

**Comment by danjford** [comment]
Ok I've got that fixed, maybe we should also display that red error message saying that no the link doesn't work?

**Comment by corysimmons** [comment]
I think we should display that error message, but we should also remove the json in <code>

This is after merge/refresh. I loaded example json then pasted and the old JSON was still there. It should be removed.

![image](https://cloud.githubusercontent.com/assets/224636/12842048/36e4d52a-cbbe-11e5-91df-2245c96801fb.png)

**Comment by danjford** [comment]
Ok I'll change it so we can customise the content of the error message also, instead of polling every few milliseconds I'll make it so that the data is only validated if there are changes.

How long after the merge did you test it? I'll take another look when I get a chance.

**Comment by corysimmons** [comment]
Ah, seems to be working now. I waited a couple minutes but I guess gh-pages didn't push to github.io yet. :\

**Comment by corysimmons** [comment]
Closing for now.
