### ISSUE TITLE
Hangs all the time

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/picky.json#35]
![image](https://cloud.githubusercontent.com/assets/224636/12831663/6f9091a8-cb63-11e5-90c6-2ebd450f532b.png)

Not sure what's going on but pickyjson.com is practically useless.

**Comment by corysimmons** [comment]
If I copy/paste a _valid_ json in, it works. If I copy paste an invalid one it hangs.

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/12831734/dc9302c2-cb63-11e5-8dc6-07cfc508431c.png)

Eh nevermind, doesn't even work. Valid on the left (`joeblau/gitignore.io/contents/README.md`) doesn't overwrite former valid on the right (octokit).

**Comment by corysimmons** [comment]
copy/paste
![image](https://cloud.githubusercontent.com/assets/224636/12831862/9c5d1e9e-cb64-11e5-8007-da2301a96302.png) hangs

but copy/paste in private works

![image](https://cloud.githubusercontent.com/assets/224636/12831867/a427f482-cb64-11e5-9427-59e5f68b6208.png)

**Comment by danjford** [comment]
I can't seem to replicate this issue at all :S Have you gone into your localStorage and cleared it all? It may be that you have an older version hanging around in the cache that doesn't match up anymore.

This could explain why it would work in incognito mode as you wouldn't have the same localStorage any more.

**Comment by corysimmons** [comment]
Cleaned out local storage, refreshed, empty, loaded sample json, worked, pasted `https://www.gitignore.io/api/node,bower` into textarea and got pic related.

![image](https://cloud.githubusercontent.com/assets/224636/12841958/a60381d2-cbbd-11e5-926f-fa9f13d6146a.png)

**Comment by corysimmons** [comment]
Ah, I see that one was addressed here https://github.com/corysimmons/picky.json/issues/34#issuecomment-180256204

I'm not sure. It was definitely hanging on me. I'll try to note steps next time it starts acting up.

**Comment by corysimmons** [comment]
Closing for now.
