### ISSUE TITLE
Care to comment it a bit more?

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/picky.json#39]
Doesn't have to be crazily commented, but it'd be helpful if you'd give it a once over and add in a few more.

**Comment by danjford** [comment]
Sure, I actually tend to use JSDoc which I think makes things a lot more clear so I could add that style of comments to most of the functions.

**Comment by corysimmons** [comment]
Sounds good. I'm not a huge fan of JSDoc out of laziness (and I just hate those `*` everywhere), but I know its merits so feel free. :+1:

**Comment by danjford** [comment]
Ok, quickly chucked a load of the normal `//` comments everywhere :P https://github.com/corysimmons/picky.json/pull/40/files

**Comment by corysimmons** [comment]
Cool thanks. :+1:
