### ISSUE TITLE
Stop 404 spamming the crap out of the console

### ISSUE THREAD

**Issue by corysimmons** [corysimmons/picky.json#4]
Right now we're testing every keyup event to see if the content is a valid JSON url.

There's no real way to test the contents to see if it ends with `.json` or if it ends with `format=json` or if it's `superapi.com/users/all`.

Is there a way to test if a URL is JSON without getting a 404? If so I'd love to implement it instead of spamming the crap out of the user's JS console. :^(

**Comment by corysimmons** [comment]
Throttle [has been added](https://github.com/corysimmons/picky.json/commit/27ffc77a507adba30e2ea7993b1a0db77e4746c3) to mitigate this problem a bit but it's still present.

**Comment by danjford** [comment]
Have added a regex so that it tests the URL to see if it is valid first. I haven't seen it spam the console since adding it in : D

**Comment by corysimmons** [comment]
Awesome. It still spams just  little bit when they enter a valid url that doesn't resolve JSON, but it's an insane amount less. Huge improvement!

**Comment by corysimmons** [comment]
Meh, pretty much fixed. I don't think we can do better.
